-------------------- Log Start | Thu Apr 24 05:36:25 2025 --------------------
data_path: /home/daniel/printer_data
is_default_data_path: False
config_file: /home/daniel/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: b58008b63adb40a8a31f7dfdb480fcc5
unix_socket_path: /home/daniel/printer_data/comms/moonraker.sock
software_version: v0.8.0-311-g65a8271
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/daniel/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]
launch_args: /home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/moonraker.py -d /home/daniel/printer_data
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 5

System Info:

***python***
  version: (3, 10, 12, 'final', 0)
  version_string: 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: x86_64
  cpu_desc: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  serial_number: 
  hardware_desc: 
  model: 
  total_memory: 12115824
  memory_units: kB

***sd_info***

***distribution***
  name: Ubuntu 22.04.4 LTS
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
Module libcamera unavailble, import failed

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice', '-.mount']
**After=['basic.target', 'system.slice', 'network-online.target', '-.mount', 'sysinit.target', 'systemd-journald.socket']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/daniel/printer_data/systemd/moonraker.env
**ExecStart=/home/daniel/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/daniel/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=daniel

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', '-.mount']
**After=['sysinit.target', 'systemd-journald.socket', 'system.slice', '-.mount', 'basic.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
Git Repo moonraker: No warnings detected
Git Repo klipper: No warnings detected
Git Repo mainsail-config: No warnings detected
Git Repo Klipper-Adaptive-Meshing-Purging: No warnings detected
Git Repo klipper-backup: No warnings detected
Git Repo crowsnest: No warnings detected
Klipper Version: v0.12.0-111-g4f00f219
2025-04-24 01:36:25,720 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-04-24 12:52:35,309 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.83', 9999)
2025-04-24 12:53:12,630 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-04-24 13:24:02,203 [server.py:_handle_term_signal()] - Exiting with signal SIGTERM
2025-04-24 13:24:02,441 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-04-24 13:24:03,658 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 16
overflow_pages: 0
entries: 52
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 42
overflow_pages: 0
entries: 100
mainsail:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 9
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 8
update_manager:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 3
overflow_pages: 11
entries: 8
webcams:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
2025-04-24 13:24:05,911 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable
2025-04-24 13:24:07,819 [server.py:main()] - Server Shutdown
-------------------- Log Start | Thu Apr 24 17:25:18 2025 --------------------
data_path: /home/daniel/printer_data
is_default_data_path: False
config_file: /home/daniel/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: b58008b63adb40a8a31f7dfdb480fcc5
unix_socket_path: /home/daniel/printer_data/comms/moonraker.sock
software_version: v0.8.0-311-g65a8271
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/daniel/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
launch_args: /home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/moonraker.py -d /home/daniel/printer_data
msgspec_enabled: False
uvloop_enabled: False
2025-04-24 13:25:18,463 [confighelper.py:read_file()] - Configuration File '/home/daniel/printer_data/config/moonraker.conf' parsed, total size: 1635 B
2025-04-24 13:25:18,463 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################
2025-04-24 13:25:20,719 [server.py:load_component()] - Component (secrets) loaded
2025-04-24 13:25:21,022 [server.py:load_component()] - Component (template) loaded
2025-04-24 13:25:21,032 [server.py:load_component()] - Component (klippy_connection) loaded
2025-04-24 13:25:25,297 [server.py:load_component()] - Component (application) loaded
2025-04-24 13:25:25,577 [server.py:load_component()] - Component (websockets) loaded
2025-04-24 13:25:26,261 [server.py:load_component()] - Component (dbus_manager) loaded
2025-04-24 13:25:26,612 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 5
2025-04-24 13:25:27,042 [server.py:load_component()] - Component (database) loaded
2025-04-24 13:25:27,285 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-04-24 13:25:27,414 [server.py:load_component()] - Component (file_manager) loaded
2025-04-24 13:25:27,606 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
.*\.lan
.*\.local
.*://localhost
.*://localhost:.*
.*://my\.mainsail\.xyz
.*://app\.fluidd\.xyz
2025-04-24 13:25:27,607 [server.py:load_component()] - Component (authorization) loaded
2025-04-24 13:25:27,657 [server.py:load_component()] - Component (klippy_apis) loaded
2025-04-24 13:25:28,450 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 10, 12, 'final', 0)
  version_string: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: x86_64
  cpu_desc: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  serial_number: 
  hardware_desc: 
  model: 
  total_memory: 12115808
  memory_units: kB

***sd_info***

***distribution***
  name: Ubuntu 22.04.4 LTS
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-04-24 13:25:28,451 [server.py:load_component()] - Component (shell_command) loaded
2025-04-24 13:25:28,451 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-04-24 13:25:28,454 [server.py:add_log_rollover_item()] - Module libcamera unavailble, import failed
2025-04-24 13:25:28,454 [server.py:load_component()] - Component (machine) loaded
2025-04-24 13:25:28,455 [server.py:load_component()] - Component (data_store) loaded
2025-04-24 13:25:28,455 [proc_stats.py:__init__()] - Unable to find 'vcgencmd', throttle checking disabled
2025-04-24 13:25:28,456 [server.py:load_component()] - Component (proc_stats) loaded
2025-04-24 13:25:28,456 [server.py:load_component()] - Component (job_state) loaded
2025-04-24 13:25:28,458 [server.py:load_component()] - Component (job_queue) loaded
2025-04-24 13:25:28,623 [server.py:load_component()] - Component (http_client) loaded
2025-04-24 13:25:28,625 [server.py:load_component()] - Component (announcements) loaded
2025-04-24 13:25:28,627 [server.py:load_component()] - Component (webcam) loaded
2025-04-24 13:25:28,629 [server.py:load_component()] - Component (extensions) loaded
2025-04-24 13:25:28,720 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/daniel/moonraker-env
2025-04-24 13:25:28,721 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/daniel/klippy-env
2025-04-24 13:25:28,771 [server.py:load_component()] - Component (update_manager) loaded
2025-04-24 13:25:28,810 [power.py:__init__()] - Power component loading devices: ['power printer_plug']
2025-04-24 13:25:28,811 [server.py:load_component()] - Component (power) loaded
2025-04-24 13:25:28,814 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-04-24 13:25:28,816 [server.py:load_component()] - Component (history) loaded
2025-04-24 13:25:28,816 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-04-24 13:25:28,821 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-04-24 13:25:29,116 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-04-24 13:25:29,116 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-04-24 13:25:29,116 [machine.py:validation_init()] - Installation version in database up to date
2025-04-24 13:25:29,225 [machine.py:check_virt_status()] - No Virtualization Detected
2025-04-24 13:25:29,910 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice', '-.mount']
**After=['system.slice', 'basic.target', 'systemd-journald.socket', '-.mount', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/daniel/printer_data/systemd/moonraker.env
**ExecStart=/home/daniel/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/daniel/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=daniel
2025-04-24 13:25:29,910 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-04-24 13:25:29,910 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-04-24 13:25:29,910 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-04-24 13:25:29,910 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-04-24 13:25:29,910 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', '-.mount']
**After=['sysinit.target', 'systemd-journald.socket', 'system.slice', '-.mount', 'basic.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2025-04-24 13:25:29,911 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2025-04-24 13:25:29,911 [server.py:_initialize_component()] - Performing Component Post Init: [power]
2025-04-24 13:25:29,911 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-04-24 13:25:29,912 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable
2025-04-24 13:25:30,948 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2025-04-24 13:25:31,929 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-04-24 13:25:33,982 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-04-24 13:25:34,523 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/daniel/printer_data/comms/moonraker.sock'
2025-04-24 13:25:34,524 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: basement
2025-04-24 13:25:34,524 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-04-24 13:25:34,778 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-04-24 13:25:34,829 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['system.slice', 'basic.target', '-.mount', 'systemd-journald.socket', 'sysinit.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2025-04-24 13:25:35,082 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-111-g4f00f219
2025-04-24 13:25:35,093 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-04-24 13:25:35,095 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-04-24 13:25:35,345 [job_state.py:_handle_started()] - Job state initialized: standby
2025-04-24 13:25:35,602 [klippy_connection.py:_check_ready()] - Klippy ready
2025-04-24 13:25:36,095 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-04-24 13:25:44,738 [base_deploy.py:log_info()] - PackageKit: Detected 141 package updates:
alsa-ucm-conf
apport
apport-gtk
apport-kde
apt
apt-utils
base-files
coreutils
cryptsetup
cryptsetup-bin
cryptsetup-initramfs
distro-info-data
dmidecode
dmsetup
dns-root-data
dpkg
dpkg-dev
e2fsprogs
firmware-sof-signed
fonts-noto-color-emoji
gir1.2-mutter-10
gir1.2-nm-1.0
gir1.2-packagekitglib-1.0
gjs
gnome-control-center
gnome-control-center-data
gnome-control-center-faces
gnome-remote-desktop
google-chrome-stable
language-pack-en
language-pack-en-base
libapt-pkg6.0
libarchive13
libcom-err2
libcryptsetup12
libdevmapper1.02.1
libdpkg-perl
libegl-mesa0
libext2fs2
libgbm1
libgjs0g
libgl1-mesa-dri
libglapi-mesa
libglx-mesa0
libgpgme11
libgpgmepp6
libldap-2.5-0
libldap-common
libmalcontent-0-0
libmbim-glib4
libmbim-proxy
libmm-glib0
libmutter-10-0
libnm0
libnss-systemd
libpackagekit-glib2-18
libpam-modules
libpam-modules-bin
libpam-runtime
libpam-systemd
libpam0g
libpcap0.8
libpulse-mainloop-glib0
libpulse0
libpulsedsp
libpython3-dev
libpython3-stdlib
libseccomp2
libsmbclient
libsnmp-base
libsnmp40
libss2
libsystemd0
libudev1
libwbclient0
libxatracker2
linux-base
logsave
mesa-va-drivers
mesa-vdpau-drivers
mesa-vulkan-drivers
modemmanager
mutter
mutter-common
network-manager
network-manager-config-connectivity-ubuntu
openssh-client
openvpn
packagekit
packagekit-tools
pci.ids
plasma-distro-release-notifier
pulseaudio
pulseaudio-module-bluetooth
pulseaudio-module-gsettings
pulseaudio-utils
python-apt-common
python3
python3-apport
python3-apt
python3-dev
python3-distupgrade
python3-gpg
python3-minimal
python3-paramiko
python3-problem-report
python3-samba
python3-update-manager
samba-common
samba-common-bin
samba-dsdb-modules
samba-libs
shim-signed
smbclient
snapd
ssh-askpass-gnome
systemd
systemd-sysv
systemd-timesyncd
tcpdump
tracker-extract
tracker-miner-fs
ubuntu-advantage-tools
ubuntu-minimal
ubuntu-pro-client-l10n
ubuntu-release-upgrader-core
ubuntu-release-upgrader-gtk
ubuntu-release-upgrader-qt
ubuntu-standard
udev
update-manager
update-manager-core
update-notifier
update-notifier-common
xdg-desktop-portal
xdg-desktop-portal-gnome
xserver-common
xserver-xephyr
xserver-xorg-core
xserver-xorg-legacy
ubuntu-pro-client
2025-04-24 13:25:45,457 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker status --porcelain -b) successfully finished
2025-04-24 13:25:45,463 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker branch --list --no-color) successfully finished
2025-04-24 13:25:45,469 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker remote get-url origin) successfully finished
2025-04-24 13:25:46,052 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker fetch origin --prune --progress) exited with return code 128
2025-04-24 13:25:46,055 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-04-24 13:25:46,556 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-04-24 13:25:46,556 [git_deploy.py:refresh_repo_state()] - Git Repo moonraker: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:46,557 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:46,856 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper status --porcelain -b) successfully finished
2025-04-24 13:25:46,862 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper branch --list --no-color) successfully finished
2025-04-24 13:25:46,867 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper remote get-url origin) successfully finished
2025-04-24 13:25:46,878 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper fetch origin --prune --progress) exited with return code 128
2025-04-24 13:25:46,880 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-04-24 13:25:47,381 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-04-24 13:25:47,381 [git_deploy.py:refresh_repo_state()] - Git Repo klipper: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:47,381 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:47,618 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config status --porcelain -b) successfully finished
2025-04-24 13:25:47,625 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config branch --list --no-color) successfully finished
2025-04-24 13:25:47,631 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config remote get-url origin) successfully finished
2025-04-24 13:25:47,642 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config fetch origin --prune --progress) exited with return code 128
2025-04-24 13:25:47,644 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-04-24 13:25:48,145 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-04-24 13:25:48,145 [git_deploy.py:refresh_repo_state()] - Git Repo mainsail-config: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:48,145 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:49,154 [base_deploy.py:log_info()] - Web Client mainsail: Github Request Error - [Errno -3] Temporary failure in name resolution
2025-04-24 13:25:49,154 [base_deploy.py:log_info()] - Web Client mainsail: Detected
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/daniel/mainsail
Local Version: v2.10.0
Remote Version: v2.10.0
Valid: True
Fallback Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.10.0/mainsail.zip
Download Size: 2081565
Content Type: application/zip
Rollback Version: v2.10.0
Rollback Repo: mainsail-crew/mainsail
2025-04-24 13:25:50,005 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging status --porcelain -b) successfully finished
2025-04-24 13:25:50,010 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging branch --list --no-color) successfully finished
2025-04-24 13:25:50,015 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging remote get-url origin) successfully finished
2025-04-24 13:25:50,025 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging fetch origin --prune --progress) exited with return code 128
2025-04-24 13:25:50,027 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-04-24 13:25:50,528 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-04-24 13:25:50,528 [git_deploy.py:refresh_repo_state()] - Git Repo Klipper-Adaptive-Meshing-Purging: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:50,528 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:50,832 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup status --porcelain -b) successfully finished
2025-04-24 13:25:50,841 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup branch --list --no-color) successfully finished
2025-04-24 13:25:50,847 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup remote get-url origin) successfully finished
2025-04-24 13:25:50,858 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup fetch origin --prune --progress) exited with return code 128
2025-04-24 13:25:50,861 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-04-24 13:25:51,362 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-04-24 13:25:51,363 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:51,363 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:51,982 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest status --porcelain -b) successfully finished
2025-04-24 13:25:51,990 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest branch --list --no-color) successfully finished
2025-04-24 13:25:51,995 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest remote get-url origin) successfully finished
2025-04-24 13:25:52,006 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest fetch origin --prune --progress) exited with return code 128
2025-04-24 13:25:52,008 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-04-24 13:25:52,510 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-04-24 13:25:52,510 [git_deploy.py:refresh_repo_state()] - Git Repo crowsnest: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:25:52,510 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-04-24 13:27:40,003 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-04-24 13:27:40,041 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.40
2025-04-24 13:27:40,042 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.40
2025-04-24 13:28:48,593 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-04-24 13:28:48,593 [application.py:log_request()] - 101 GET /websocket (127.0.0.1) [_TRUSTED_USER_] 1.78ms
2025-04-24 13:28:48,594 [websockets.py:open()] - Websocket Opened: ID: 139802761805728, Proxied: True, User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0, Host Name: localhost
2025-04-24 13:28:48,637 [websockets.py:_handle_identify()] - Websocket 139802761805728 Client Identified - Name: mainsail, Version: 2.10.0, Type: web
2025-04-24 13:29:18,047 [job_state.py:_status_update()] - Job Started: flexbatterAAx2_1h39m_0.20mm_205C_PLA_ENDER3S1.gcode
2025-04-24 13:54:19,627 [job_state.py:_status_update()] - Job Started: flexbatterAAx2_1h39m_0.20mm_205C_PLA_ENDER3S1.gcode
2025-04-24 14:30:29,127 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
