-------------------- Log Start | Tue May  6 16:26:18 2025 --------------------
data_path: /home/daniel/printer_data
is_default_data_path: False
config_file: /home/daniel/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: b58008b63adb40a8a31f7dfdb480fcc5
unix_socket_path: /home/daniel/printer_data/comms/moonraker.sock
software_version: v0.8.0-311-g65a8271
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/daniel/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
launch_args: /home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/moonraker.py -d /home/daniel/printer_data
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 5

System Info:

***python***
  version: (3, 10, 12, 'final', 0)
  version_string: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: x86_64
  cpu_desc: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  serial_number: 
  hardware_desc: 
  model: 
  total_memory: 12115808
  memory_units: kB

***sd_info***

***distribution***
  name: Ubuntu 22.04.4 LTS
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
Module libcamera unavailble, import failed

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice', '-.mount']
**After=['system.slice', 'basic.target', 'systemd-journald.socket', '-.mount', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/daniel/printer_data/systemd/moonraker.env
**ExecStart=/home/daniel/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/daniel/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=daniel

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['system.slice', 'basic.target', '-.mount', 'systemd-journald.socket', 'sysinit.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
Git Repo moonraker: No warnings detected
Git Repo klipper: No warnings detected
Git Repo mainsail-config: No warnings detected
Git Repo Klipper-Adaptive-Meshing-Purging: No warnings detected
Git Repo klipper-backup: No warnings detected
Git Repo crowsnest: No warnings detected
Klipper Version: v0.12.0-111-g4f00f219
2025-05-06 12:26:18,155 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.131
2025-05-06 12:26:18,156 [application.py:log_request()] - 101 GET /websocket (192.168.0.131) [_TRUSTED_USER_] 1.19ms
2025-05-06 12:26:18,156 [websockets.py:open()] - Websocket Opened: ID: 139802771191360, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0, Host Name: 192.168.0.40
2025-05-06 12:26:18,193 [websockets.py:_handle_identify()] - Websocket 139802771191360 Client Identified - Name: mainsail, Version: 2.10.0, Type: web
2025-05-06 12:26:30,601 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-05-06 12:26:31,859 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-05-06 12:26:31,884 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['network-online.target', 'sysinit.target', 'systemd-journald.socket', 'basic.target', '-.mount', 'system.slice']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2025-05-06 12:26:33,900 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-05-06 12:26:33,901 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-05-06 12:26:34,151 [job_state.py:_handle_started()] - Job state initialized: standby
2025-05-06 12:26:34,411 [klippy_connection.py:_check_ready()] - Klippy ready
2025-05-06 12:26:35,157 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-05-06 13:30:33,273 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.131
2025-05-06 14:04:06,090 [websockets.py:on_close()] - Websocket Closed: ID: 139802771191360 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 7.93
2025-05-06 17:26:21,167 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.83', 9999)
2025-05-06 17:32:13,092 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-05-06 17:33:41,227 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.83', 9999)
2025-05-06 17:38:20,425 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-05-06 17:38:58,923 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.83', 9999)
2025-05-06 17:42:33,605 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-05-06 18:47:35,151 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.83', 9999)
2025-05-06 18:50:13,387 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-05-06 19:14:54,059 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.83', 9999)
2025-05-06 19:15:15,214 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-05-06 21:11:02,847 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2025-05-06 21:11:02,854 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1746580233.089461, Usage: 0.68%, Memory: 51860 kB
System Time: 1746580234.089284, Usage: 0.65%, Memory: 51860 kB
System Time: 1746580235.090269, Usage: 0.63%, Memory: 51860 kB
System Time: 1746580236.091737, Usage: 0.67%, Memory: 51860 kB
System Time: 1746580237.091924, Usage: 0.8%, Memory: 51860 kB
System Time: 1746580238.093431, Usage: 0.67%, Memory: 51860 kB
System Time: 1746580239.093781, Usage: 1.01%, Memory: 51860 kB
System Time: 1746580240.093317, Usage: 0.83%, Memory: 51860 kB
System Time: 1746580241.095159, Usage: 0.67%, Memory: 51860 kB
System Time: 1746580242.095090, Usage: 0.59%, Memory: 51860 kB
System Time: 1746580243.096539, Usage: 0.61%, Memory: 51860 kB
System Time: 1746580244.098100, Usage: 0.66%, Memory: 51860 kB
System Time: 1746580245.100402, Usage: 0.66%, Memory: 51860 kB
System Time: 1746580246.099549, Usage: 0.82%, Memory: 51860 kB
System Time: 1746580247.100215, Usage: 0.76%, Memory: 51860 kB
System Time: 1746580248.101239, Usage: 0.54%, Memory: 51860 kB
System Time: 1746580249.104786, Usage: 0.92%, Memory: 51860 kB
System Time: 1746580250.105285, Usage: 1.03%, Memory: 51860 kB
System Time: 1746580251.102885, Usage: 0.85%, Memory: 51860 kB
System Time: 1746580252.104825, Usage: 0.62%, Memory: 51860 kB
System Time: 1746580253.104443, Usage: 0.62%, Memory: 51860 kB
System Time: 1746580254.105095, Usage: 0.65%, Memory: 51860 kB
System Time: 1746580255.107552, Usage: 0.56%, Memory: 51860 kB
System Time: 1746580256.108463, Usage: 0.99%, Memory: 51860 kB
System Time: 1746580257.107600, Usage: 1.15%, Memory: 51860 kB
System Time: 1746580258.109825, Usage: 0.98%, Memory: 51860 kB
System Time: 1746580259.110540, Usage: 0.74%, Memory: 51860 kB
System Time: 1746580260.110116, Usage: 1.0%, Memory: 51860 kB
System Time: 1746580261.111262, Usage: 0.57%, Memory: 51860 kB
System Time: 1746580262.113038, Usage: 0.57%, Memory: 51860 kB
CPU Temperature: 46.0
